packages:
  - 'packages/*'
allowBuilds:
  '3': true
  ' ': true
  '-': true
  b: true
  c: true
  d: true
  e: true
  i: true
  l: true
  n: true
  o: true
  q: true
  r: true
  s: true
  t: true
  u: true
